### ISSUE TITLE
base de datos

### ISSUE THREAD

**Issue by abubelinha** [kix2902/Santoral#1]
¿Es posible actualizar la base de datos?
No sé qué archivo concreto habría que modificar.

**Comment by kix2902** [comment]
Los santos se solicitan a un servidor web, no están almacenados en la aplicación

**Comment by abubelinha** [comment]
Gracias.  ¿Y de qué servidor se trata?  
Me gustaría poder descargar/imprimir la lista (para unos calendarios).

**Comment by kix2902** [comment]
El servidor que uso es uno propio, pero si buscas por internet hay muchas webs con listas de santos y alguna puede tener API

**Comment by abubelinha** [comment]
Ah OK, no te había entendido.  Gracias.
